models/Products.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "products".
 *
 * @property int $product_id
 * @property string $product_code
 * @property string $product_name
 * @property string $product_size
 * @property string $product_location
 * @property int $product_price
 */
class Products extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['product_code', 'product_name', 'product_size', 'product_price'], 'required'],
            [['product_price'], 'integer'],
            [['product_code'], 'string', 'max' => 100],
            [['product_name'], 'string', 'max' => 20],
            [['product_size'], 'string', 'max' => 10],
            [['product_location'], 'string', 'max' => 200],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'product_id' => 'Product ID',
            'product_code' => 'Product Code',
            'product_name' => 'Product Name',
            'product_size' => 'Product Size',
            'product_location' => 'Product Location',
            'product_price' => 'Product Price',
        ];
    }
}

controllers/ProductsController.php
<?php

namespace app\controllers;

use app\models\AuditReport;
use app\models\CartProducts;
use app\models\OrderProducts;
use app\models\Products;
use app\models\Users;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\Response;
use app\helpers\ConditonBuilder;
use app\helpers\CrudConstants;

class ProductsController extends  SiteController
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['products'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['savecart'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['countcart'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['audit'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['cartitems','deleteitem','orderitems'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionProducts()
    {

        $model=new Products();
        $AuditLog=new AuditReport();
        $AuditLog->user_action=$AuditLog::R;
        $AuditLog->description_action='View Products Available';
        $AuditLog->table_affected=Products::getTableSchema()->name;
        $AuditLog->user_id=\Yii::$app->user->identity->user_id;
        $AuditLog->save(false);

        $ter=$model::find()->asArray()->all();



        return $this->render('products', [
            'model' => $ter,
        ]);
    }

    public function actionSavecart()
    {
        $model = new CartProducts();

        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
        if (Yii::$app->request->isAjax ) {
            $validate=$model::find()->where(['product_id'=>$_POST['product_id']])->all();
          //  var_dump($_POST['product_id']);die;
            if($validate) {
                echo 'Item already added to cart: ID=> '.$_POST['product_id'];
                exit;
            }else
            $model->user_id=Yii::$app->user->identity->user_id;
            $model->product_id=$_POST['product_id'];
            $model->product_name=$_POST['product_name'];
            $model->product_price=$_POST['product_price'];
            $model->product_code=$_POST['product_code'];
            $model->product_size=$_POST['product_size'];
            $model->save(false);
            $transaction->commit();
         echo  "Data inserted";
        }}
        catch(\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }
    }
    public function actionCountcart(){

        if (Yii::$app->request->isAjax) {
            $user_id = Yii::$app->user->identity->user_id;
            $model = new CartProducts();
            $result = $model::find()->where(['user_id' => $user_id])->count();

            return $result;
        }

    }


    public function actionCartitems()
    {    $model = new CartProducts();
        $condition = new ConditonBuilder();
        $gt = Yii::$app->user->identity->user_id;
        $conditionrt = $model::find()->where(['user_id' => $gt])->asArray()->all();
        $condition->addCondition('user_id IN(select user_id from cart_products where user_id=:id)', [':id' => $gt]);
        // var_dump($condition); exit;




        if (Yii::$app->request->post('hasEditable')) {
            // instantiate your book model for saving
            $bookId = Yii::$app->request->post('editableKey');
            $model = CartProducts::findOne($bookId);

            // store a default json response as desired by editable
            $out = Json::encode(['output'=>'', 'message'=>'']);

            // fetch the first entry in posted data (there should only be one entry
            // anyway in this array for an editable submission)
            // - $posted is the posted data for Book without any indexes
            // - $post is the converted array for single model validation
            $posted = current($_POST['CartProducts']);
            $post = ['CartProducts' => $posted];

            // load model like any single model validation
            if ($model->load($post)) {
                // can save model or do something before saving model
                $model->save();

                // custom output to return to be displayed as the editable grid cell
                // data. Normally this is empty - whereby whatever value is edited by
                // in the input by user is updated automatically.
                $output = '';

                // specific use case where you need to validate a specific
                // editable column posted when you have more than one
                // EditableColumn in the grid view. We evaluate here a
                // check to see if buy_amount was posted for the Book model
                if (isset($posted['quantity'])) {
                    $output = Yii::$app->formatter->asInteger($model->quantity);
                }

                // similarly you can check if the name attribute was posted as well
                // if (isset($posted['name'])) {
                // $output = ''; // process as you need
                // }
                $out = Json::encode(['output'=>$output, 'message'=>'']);
            }
            // return ajax json encoded response and exit
            echo $out;
            return;
        }




        return $this->render('cartitems',
            array('dataProvider'=> CartProducts::searchModel(10,'cart_id',$condition),
                 'model'=>$model,
                ));
    }


    public function actionDeleteitem($product_id){


        $rem= new CartProducts();
        $Auditlog=new AuditReport();
        $countrem=$rem::find()->where(['user_id'=>\Yii::$app->user->identity->user_id])->count();
        $connection= \Yii::$app->db;
        $transaction=$connection->beginTransaction();
        $model=CartProducts::find()->where(['cart_product_id'=>$product_id])->one();
        if($model){
            $model->delete();
            \Yii::$app->session->setFlash('success','Item Removed');
            //log action into Audit Table
            $Auditlog->user_action=$Auditlog::D;
             $Auditlog->description_action='Removed Item From Cart';
             $Auditlog->table_affected=CartProducts::getTableSchema()->name;
             $Auditlog->user_id=\Yii::$app->user->identity->user_id;
             $Auditlog->save(false);
            $transaction->commit();

            if($countrem >= 1){

            return   $this->redirect(['products/cartitems']);
            }else{
           return  $this->redirect(['products/products']);
            \Yii::$app->session->setFlash('error','Dear user select products items');}

        }else{
            $transaction->rollBack();
        \Yii::$app->session->setFlash('error','Item cannot be removed');
      return $this->redirect(['products/cartitems']);}

    }
    public function actionOrderitems($user_id){
        $model=CartProducts::find()->where(['user_id'=>$user_id])->asArray()->all();
        $final_price=0;

            foreach ($model as $fr => $value){
               // var_dump(count($model)); exit;
                $final_price +=$value['product_price']*$value['cart_quantity'];
            }

        $final=new OrderProducts();
        if($model){
            $connection= \Yii::$app->db;
            $transaction=$connection->beginTransaction();
            try{
           if($final->load(\Yii::$app->request->post())){

               foreach ($model as $fr => $value){
               $final->product_id=$value['product_id'];
              // $final->county_name=$_POST['Location']['county_name'];
               $final->order_product_code=$value['order_product_code'];
               $final->order_product_name=$value['order_product_name'];
               $final->order_product_size=$value['order_product_size'];
               $final->order_quantity=$value['cart_quantity'];
               $final->product_price=$final_price;
               $final->user_id=$user_id;
               $final->save(false);
               $transaction->commit();
               return $this->redirect(['products/products']);}

           }} Catch (\Exception $e){
                $transaction->rollBack();
                \Yii::$app->session->setFlash('error', 'Abort Abort!!! Immediate evac Co-ordinates Alpha 10 Bravo 50 Tango Down'. $e );
                return $this->redirect(['products/cartitems']);
            }

        }

   return $this->render('orderitems',['model'=>$final,'dr'=>$final_price]);

    }

    public function actionAudit(){

        $model=new AuditReport();
        $condition = new ConditonBuilder();
        $gt = Yii::$app->user->identity->user_id;
       // $conditionrt = $model::find()->where(['user_id' => $gt])->asArray()->all();
        $condition->addCondition('user_id IN(select user_id from audit_report )', [':id' => $gt]);






        return $this->render('audit',
            array('dataProvider'=> AuditReport::searchModel(10,'audit_id',$condition),
                'model'=>$model,
            ));

    }


}

views/products/audit.php
<?php

use app\helpers\MyKartikGridView;
use kartik\form\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
rmrevin\yii\fontawesome\AssetBundle::register($this);


$this->title = 'Audit Report';
?>


<div class="row">

    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <!--            <h4><i class="icon fa fa-check"></i>Saved!</h4>-->
            <?= Yii::$app->session->getFlash('success') ?>
        </div>
    <?php endif; ?>


    <?php if (Yii::$app->session->hasFlash('error')): ?>
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <!--            <h4><i class="icon fa fa-check"></i>Saved!</h4>-->
            <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>

    <div >

        <?= app\helpers\MyKartikGridView::widget([
            'dataProvider' => $dataProvider,
            'searchField' => false,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn',
                ],
                [
                    'label' => 'User Action',
                    'value' => 'user_action',
                ],
                [
                    'label' => 'Action Description',
                    'value' => 'description_action',
                ],
                [
                    'label' => 'Table Affected',
                    'value' => 'table_affected',

                ],
                [
                    'label' => 'Date',
                    'value' => 'date_log',
                ],
                [
                    'label' => 'Username(Email Address)',
                    'value' => 'user.email_address',
                ],

            ],

            'exportConfig' => [
                MyKartikGridView::CSV => ['label' => 'Export as CSV', 'filename' => 'Audit Report -' . date('d-M-Y')],
                MyKartikGridView::HTML => ['label' => 'Export as HTML', 'filename' => 'Audit Report -' . date('d-M-Y')],
                MyKartikGridView::PDF => ['label' => 'Export as PDF', 'filename' => 'Audit Report-' . date('d-M-Y')],
                MyKartikGridView::EXCEL => ['label' => 'Export as EXCEL', 'filename' => 'Audit Report -' . date('d-M-Y')],
                MyKartikGridView::TEXT => ['label' => 'Export as TEXT', 'filename' => 'Audit Report -' . date('d-M-Y')],
            ],

        ]); ?>
    </div>
</div>

views/products/cartitems.php
<?php

use app\helpers\MyKartikGridView;
use kartik\form\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
rmrevin\yii\fontawesome\AssetBundle::register($this);


$this->title = 'Check-Out Items';
?>


<div class="row">

      <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
<!--            <h4><i class="icon fa fa-check"></i>Saved!</h4>-->
            <?= Yii::$app->session->getFlash('success') ?>
        </div>
    <?php endif; ?>


    <?php if (Yii::$app->session->hasFlash('error')): ?>
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
<!--            <h4><i class="icon fa fa-check"></i>Saved!</h4>-->
            <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>

    <div class="col-md-10">

        <?= app\helpers\MyKartikGridView::widget([
            'dataProvider' => $dataProvider,
             'searchField' =>false,
            'createButton' => [
                'visible' => true,
                'label' => 'Order Items','data-toggle'=>'modal','url' => Url::to(['products/orderitems','user_id'=>\Yii::$app->user->identity->user_id ]), 'modal' => true,
            ],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn',
                ],
                [
                    'label' => 'Email Address',
                    'value' => 'user.email_address',
                ],
                [
                    'label' => 'Product Name',
                    'value' => 'cart_product_name',
                ],
                [
                    'label' => 'Product Size',
                    'value' => 'cart_product_size',

                ],
                [
                    'label' => 'Product Price Per Item',
                    'value' => 'product_price',
                ],
                [
                    'class'=>'kartik\grid\EditableColumn',
                    'attribute'=>'cart_quantity',
                    'editableOptions'=>[
                        'header'=>'Add number of items to order',
                        'inputType'=>\kartik\editable\Editable::INPUT_SPIN,
                        'options'=>['pluginOptions'=>['min'=>0, 'max'=>5000]]
                    ],
                    'hAlign'=>'right',
                    'vAlign'=>'middle',
                    'width'=>'50px',
                    'format'=>['integer'],
                    'pageSummary'=>true
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{detailbank}<br>{DeleteUser}',//{delete}
                    'visibleButtons' => [
                        'update' =>true,
                        'Delete'=>false,
                    ],
                    'buttons' => [
                        'detailbank' => function ($url, $model) {

                            $url = Url::to(['products/deleteitem', 'product_id' => $model->cart_product_id]);
                            return Html::a('<i class="fa fa-trash-o" aria-hidden="true"></i> Remove Item', $url, [
                                'title' => 'Finalize',
                                'class' => 'always_open_link',
                                'data' => [
                                    'confirm' => 'Are you sure you want to remove this item?',
                                    'method' => 'post',
                                ]
                            ]);
                        },

                    ],],

            ],

            'exportConfig' => [
                MyKartikGridView::CSV => ['label' => 'Export as CSV', 'filename' => 'My Items to order -' . date('d-M-Y')],
                MyKartikGridView::HTML => ['label' => 'Export as HTML', 'filename' => 'My Items to order -' . date('d-M-Y')],
                MyKartikGridView::PDF => ['label' => 'Export as PDF', 'filename' => 'My Items to order -' . date('d-M-Y')],
                MyKartikGridView::EXCEL => ['label' => 'Export as EXCEL', 'filename' => 'My Items to order -' . date('d-M-Y')],
                MyKartikGridView::TEXT => ['label' => 'Export as TEXT', 'filename' => 'My Items to order -' . date('d-M-Y')],
            ],

        ]); ?>
    </div>
</div>

views/products/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>products/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

views/products/orderitems.php
<?php

use app\helpers\Functions;
use app\models\Location;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OrderProducts */
/* @var $form yii\widgets\ActiveForm */
$template = '{label}{input}{error}';
$this->title = 'Final order details';
//if ($model->pos_device_id) {
//    $this->title = "Update Mobile Device";
//}
?>

<div class="modal-content">

    <?php $form = ActiveForm::begin([
        'enableClientValidation' => true,
        'options' => [
            'class' => 'modal-dialog',
        ],]); ?>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?= $this->title ?></h4>
    </div>
    <div class="modal-dialog">

        <div class="modal-dialog">
            <div class="md-form mb-3">
                <label for="finprice">Final Price: Ksh. <?= $dr ?></label>

            </div>

            <div class="md-form mb-3">
                <?= $form->field($model, 'phone_number')->textInput(['maxlength' => true]) ?>
            </div>
            <br>
            <div class="md-form mb-3">
                <?= $form->field($model, 'county_name')->dropDownList(
                    ArrayHelper::map(Location::find()->select(['county_id','county_name'])->all(),'county_name','county_name'),
                    ['prompt' => 'Select']
                ) ?>
            </div>
            <br>
            <div class="md-form mb-3">
                <?= $form->field($model, 'location_description')->textarea(['maxlength' => true]) ?>
            </div>


        </div>

        <div class="row">
            <?= Functions::renderSubmitSearchField(
                'Order',
                'btn btn-primary',
                'col-sm-6'
            ) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>

</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"> </script>
<script>
    $(document).ready(function(){
        $(".close").click(function(){
            $('.modal-dialog').hide();
        });
    });
</script>

views/products/products.php
<?php

/* @var $this yii\web\View */

use yii\bootstrap\Button;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Aqua Products Available';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php if (Yii::$app->session->hasFlash('success')): ?>
    <div class="alert alert-success alert-dismissable">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
        <!--            <h4><i class="icon fa fa-check"></i>Saved!</h4>-->
        <?= Yii::$app->session->getFlash('success') ?>
    </div>
<?php endif; ?>


<?php if (Yii::$app->session->hasFlash('error')): ?>
    <div class="alert alert-danger alert-dismissable">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
        <!--            <h4><i class="icon fa fa-check"></i>Saved!</h4>-->
        <?= Yii::$app->session->getFlash('error') ?>
    </div>
<?php endif; ?>
<div class="site-products">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <div class="w3-container w3-teal">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>

    <div class="items">
        <button  type="button" class="btn btn-primary">
            Items in Cart <span class="badge badge-light" id="CartNo">0</span>
        </button>

    </div>
    <br><br><br>
    <div class="check">
        <?= Html::a('View Items In Cart', ['products/cartitems'], ['class'=>'btn btn-primary']) ?>
    </div>
    <br><br><br>


    <div class="w3-row-padding w3-margin-top">
        <?php foreach ($model as  $value) {//Opening foreach.

            ?>

            <div class="w3-third">
                <div class="w3-card">

                    <?= Html::img('@web/Aquaproducts/'.$value['product_location']);?>
                    <div class="w3-container">
                        <h5 class="id" ><span class="label label-primary" style="color:white"><?= $value['product_id']?></span></h5>
                        <h5 class="name"><span class="label label-primary" style="color:white"><?= $value['product_name']?></span></h5>
                        <h5 class="price"><span class="label label-warning" style="color:blue"><?= $format='Ksh. '. $value['product_price']?></span></h5>
                        <h5 class="code" hidden><span class="label label-warning" style="color:blue"><?= $value['product_code']?></span></h5>
                        <h5 class="size" hidden><span class="label label-warning" style="color:blue"><?= $value['product_size']?></span></h5>
                        <div class="eset">
                            <?=  Button::widget([
                                'label' => 'Add Cart',
                                'id'=>'haha',
                                'options' => ['class' => 'btn btn-danger'],
                            ]);?>
                        </div>
                    </div>

                </div>
            </div>
        <?php }//closing foreach?>
    </div><!-- .w3-row-padding -->

</div>


</div>

<style>
    .items{
        position: absolute;
        right: 105px;
    }
    .check{
        position: absolute;
        right: 105px;
    }

</style>


<script src="https://code.jquery.com/jquery-3.4.1.min.js"> </script>
<script>
    $(document).ready(function () {
        //Add cart items to database
        $('.eset').click(function () {
            var cripe = $(this).parent().find('.price').text();
            var price=cripe.replace('Ksh. ',' ');
            $.ajax({
                method: 'POST',
                url: '<?php echo Yii::$app->request->baseUrl. '/products/savecart' ?>',
                data:{product_id:$(this).parent().find('.id').text(), product_name:$(this).parent().find('.name').text(), product_price:price, product_code:$(this).parent().find('.code').text(),product_size:$(this).parent().find('.size').text()},
                success: function(data) {
                    alert(data);
                },
            });
            $.ajax({
                method: 'GET',
                url: '<?php echo Yii::$app->request->baseUrl. '/products/countcart' ?>',
                success: function (data) {
                    if(data >= 1){
                        $('.check').show()
                    }else
                        $('.check').hide()
                },
            }).done(function (data) {
                $('#CartNo').html(data);
            });
        });
    });
</script>

<script>

    $.ajax({
        method: 'GET',
        url: '<?php echo Yii::$app->request->baseUrl. '/products/countcart' ?>',
        success: function (data) {
            // alert('It has worked');
        },
    }).done(function (data) {
        $('#CartNo').html(data);
        if(data >= 1){
            $('.check').show()
        }else
            $('.check').hide()
    });

</script>